{
    task_name: "Joint Text-Layout Reconstruction",                   # All, Layout Modeling, Visual Text Recognition, Joint Text-Layout Reconstruction

    # Path config
    model_name_or_path: "models/all",   # Path to model weight
    output_dir: "./test",               # Path to save test images
    data_dir: "./data",                 # Path to data directory

    # Model config
    max_seq_length: 512,
    image_size: 224,
    max_seq_length_decoder: 512,
    model_type: "UdopUnimodel",

    # Test config
    do_train: false,
    do_eval: false,
    do_predict: true,
    dataloader_num_workers: 4,
    do_save_visualize: true             # Save plt figures 
}